### ISSUE TITLE
Spelling/grammar in traits_suprememelee.xml

### ISSUE THREAD

**Issue by fikealox** [emipa606/SupremeMelee#2]
There are some spelling/grammar errors in the SupremeMelee_QuickReflexes trait in Defs>TraitDefs>traits_suprememelee.xml:

- the description of both degrees of the trait omit the possessive apostrophe (i.e. they read "{PAWN_nameDef} reflexes ..." rather than "{PAWN_nameDef}'s reflexes").

- the label for the second degree of the trait has a typo (i.e. it reads "transcendant reflexes" rather than "transcendent reflexes").

I've attached a file in which those errors are corrected (as a .txt since I can't upload a .xml).

Thanks so much for all your hard work.  You're the best.

[Traits_SupremeMelee.txt](https://github.com/emipa606/SupremeMelee/files/6831412/Traits_SupremeMelee.txt)

**Comment by emipa606** [comment]
Thanks! Included in the latest version
